name: graphcast
channels:
  - defaults
  - conda-forge
  - nvidia/label/cuda-11.8.0
dependencies:
  - autopep8
  - cartopy
  - cuda
  - dask
  - dm-tree
  - ipykernel
  - ipython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - psy-view
  - python
  - rtree
  - ruff
  - scipy
  - trimesh
  - typing_extensions
  - xarray
  - zarr
  - pip:
    - chex
    - dm-haiku
    - jraph
    - -e .